gravatar:
  size: 60
  list_size: 50
per_page_count: 15
maximum_email_length: 256
maximum_micropost_length: 140
maximum_name_length: 60
maximum_img_size: 5
minimum_password_length: 8

resize_size: 400
remember_yes: 1
